### ISSUE TITLE
bar_CatCatum - Colores de la categoría 

### ISSUE THREAD

**Issue by facarranza** [datasketch/hgchmagic#125]
No se muestran los colores de las barras en  bar_CatCatum en el siguiente ejemplo

#versión: 71df7f8c4e6496e3a71aebba8537eb070a545d56

opts <- list(
  theme = list(
    title = "title",
    title_align = "center",
    tiltle_size = 15,
    marker_radius = 0,
    text_family = "Barlow",
    legend_family = "Barlow",
    text_color = "#0F1116",
    background_color = "#FFFFFF",
    grid_x_width = 0,
    label_wrap = 70,
    format_sample_num = "1,234.56",
    axis_line_y_size = 1,
    axis_line_x_size = 1,
    axis_line_color = "#CECECE",
    title_size = 17,
    title_weight = 500,
    palette_colors = c("#47BAA6", "#151E42", "#FF4824", "#FFCF06", "#FBCFA4", "#FF3D95", "#B13168")
  )
)

data <- tibble(valor = c(1,2,3,1,1,2,3,1,3,2),
               pais = c("argentina","argentina","brazil","argentina","argentina","bolivia","colombia","peru","argentina","el salvador"),
               count = c(10,25,3,10,31,23,3,13,3,21))
data$valor <- as.character(data$valor)
opts$theme$color_by = "valor"
hgch_bar_CatCatNum(data, opts=opts)

**Comment by CamilaAchuri** [comment]
@pablotis esto quedó solucionado
