### ISSUE TITLE
which process should be executed first: order categories (either by order or sort parameters) or assigning colors to categories (by palette_colors parameter)?

### ISSUE THREAD

**Issue by brazadas** [datasketch/hgchmagic#84]
For example:

`hgch_bar_CatNum(data.frame(a = c("w", "e", "f"), b = c(3, 8, 7)), palette_colors = c("red", "blue", "purple"), color_by = "a")` is going to return this:

![Screenshot from 2020-09-28 11-20-59](https://user-images.githubusercontent.com/19413995/94459298-c35a9c80-017c-11eb-9bc8-4f36590ee347.png)

But now if I use the order parameter to organize categories as I like, colors are assigned before the order process happens, so the initial order of categories establish the color mapping:

`hgch_bar_CatNum(data.frame(a = c("w", "e", "f"), b = c(3, 8, 7)), palette_colors = c("red", "blue", "purple"), color_by = "a", order = "f")`

![Screenshot from 2020-09-28 11-23-43](https://user-images.githubusercontent.com/19413995/94459613-3532e600-017d-11eb-9b1d-0ac3b9c106b8.png)

On the other hand, the process of sorting results with respect of ascending or descending order of values, is called before mapping colors:

 `hgch_bar_CatNum(data.frame(a = c("w", "e", "f"), b = c(3, 8, 7)), palette_colors = c("red", "blue", "purple"), color_by = "a", sort = "asc")`

![Screenshot from 2020-09-28 11-30-18](https://user-images.githubusercontent.com/19413995/94460206-010bf500-017e-11eb-97d8-30b386649fc2.png)

What is the desired behaviour?
For me it make sense to order first (if requested) and then map the colors

**Comment by CamilaAchuri** [comment]
Mientras cambie el color de orden y mañana miro bien que es

**Comment by brazadas** [comment]
es el orden en que se ejecutan las cosas en `hgchmagic_prep` (primero se mapea el color y luego se ordena); la pregunta es: ¿cuál es el comportamiento deseado? A mi me parece mejor que primero se ordene y luego se mapee el color, pero bueno no sé qué sea lo mejor. En términos de código simplemente es el orden en que se llaman las funciones de orden y color

**Comment by jpmarindiaz** [comment]
Una vez el color es asignado, es raro que se cambie el color automáticamente si se llama el sort, la gente se confundiría. Por eso creo que primero es el mapeo de color y luego ordenar si entendí bien. Visualmente los colores llevan mucha información a las personas, entonces cambiárselos con las otras opciones no estaría bien

**Comment by brazadas** [comment]
ajaj yo pienso al revés pero bueno será mi contra-intuición de siempre.
@CamilaAchury entonces el ordenar con sort y la asignación de color están bien; lo que faltaría sería la ordenada con `order` -- segunda imagen -- (debería estar primero que la asignación de color para que el color quede como el usuario quiere sin importar el orden como dice @jpmarindiaz), ¿quiere que lo haga?

**Comment by CamilaAchuri** [comment]
No se si entendí bien, el color de las categorías debería quedar el mismo aún cuando se haga el sort, si?.
@brazadas  por mi no hay problema, agradecida de ante mano

**Comment by brazadas** [comment]
jajajja @CamilaAchury  qué es este bello lenguaje tuyo. @jpmarindiaz releyendo creo que estamos diciendo lo mismo: 

si se escogen colores y sort, los colores quedan fijos (en posición) y las barras cambian de orden i.e. la primera barra será siempre amarilla , la segunda azul, ..., sin importar cuál categoría representen

ahora, si se escogen colores y orden explícito de categorías ¿qué pasa?: yo creo que se deberían ordenar (según el orden deseado) y luego se asigna el color: esto no está pasando ahora, primero se asigna el color y luego se ordena, entonces, si uno pone un orden y unos colores, no corresponden  salenlas barras ordenadas pero el color mapeado según el orden original que supongo, es alfabético (segundo ejemplo de arriba)

**Comment by jpmarindiaz** [comment]
jaja hazlo como consideres mejor, ya me perdí :)

**Comment by brazadas** [comment]
jaja ok
